= {{ provider.company }}: Invoice
:doctype: article
:imagesdir: {{ invoice.assets_path }}
{%- if invoice.dates.paid %}
:page-foreground-image: image::paid-stamp.svg[pdfwidth=35%,fit=none,position=top]
{%- endif %}

{%- assign project = invoice.project | default: client.defaults.project | default: settings.defaults.project | default: "Consulting" %}
{%- assign currency_symbol = client.defaults.currency_symbol | default: settings.defaults.currency_symbol | default: "$" %}
{%- assign date_format = client.defaults.date_format | default: settings.defaults.date_format | default: "%Y-%m-%d" %}
{%- assign item_date_format = client.defaults.item_date_format | default: settings.defaults.item_date_format | default: "%m/%d" %}
{%- assign invoice_tables_layout = config.invoice_tables_layout | default: "horizontal" %}
{%- if invoice_tables_layout == "horizontal" %}
{%-   assign table_cols = "1,1" %}
{%- else %}
{%-   assign table_cols = "1" %}
{%- endif %}

[cols="{{ table_cols }}", frame="none", grid="none"]
|====
a|

[cols="1,3", grid="none", options="header"]
!===
2+! Client Information
s! Name
! {{ client.name }}

s! Address
! {{ client.address }}

s! Contact
! {{ client.contact.name }}

s! Email
! {{ client.contact.email }}

s! Phone
! {{ client.phone }}

s! Currency
! {{ client.defaults.currency | default: settings.defaults.currency | default: "USD" }}
!===

a|

[cols="1,3", grid="none"]
!===
2+! Invoice Details

s! Invoice ID
! {{ invoice.id }}

s! Project
! {{ project }}

s! Issued
! {{ invoice.dates.sent }}

s! Billing Period
! {{ invoice.dates.start }} - {{ invoice.dates.end }}

s! Due
! {{ invoice.dates.due }}{% if invoice.overdue %} *(Overdue)*{% endif %}

{% if invoice.dates.paid %}
s! Paid
! {{ invoice.dates.paid | date: date_format }}
{%- endif %}
!===

|====


[cols="3,1,1,1,1", options="header", grid="rows"]
|===
| Description
| Date
| Quantity
| Unit Price
| Total
{%- assign subtotal = 0 %}
{%- assign invoice_memo = invoice.memo %}
{% for item in invoice.items %}
{%- unless item.type == "monthly" or item.type == "per-invoice" %}
{%- assign default_price = client.defaults.fees.hourly[item.type] | default: 0 %}
{%- assign item_price = item.cost | default: default_price %}
{%- assign item_count = item.count | default: 1 %}
{%- assign item_total = item_count | times: item_price %}
{%- assign subtotal = subtotal | plus: item_total %}
| {{ item.desc }}
| {% if item.date %}{{ item.date | date: item_date_format }}{% else %}N/A{% endif %}
| {{ item_count }}
| {{ item_price | format_decimal | number_delimited }}
| {{ item_total | format_decimal | number_delimited }}
{%- endunless %}
{% endfor %}
{%- assign monthlies = invoice.items | where: "type", "monthly" %}
{%- assign fixed_fees = invoice.items | where: "type", "per-invoice" | concat: monthlies %}
{% for item in fixed_fees %}
{%- assign default_price = client.defaults.fees.fixed[item.type] | default: 0 %}
{%- assign item_price = item.cost | default: default_price %}
{%- assign item_count = item.count | default: 1 %}
{%- assign item_total = item_count | times: item_price %}
{%- assign subtotal = subtotal | plus: item_total %}
| {{ item.desc }}
| {% if item.date %}{{ item.date | date: item_date_format }}{% else %}N/A{% endif %}
| {{ item_count }}
| {{ item_price | format_decimal | number_delimited }}
| {{ item_total | format_decimal | number_delimited }}
{% endfor %}

4+h| Total | {{ currency_symbol }}{{ subtotal | format_decimal | number_delimited }}

{%- if invoice.payments %}
{%-   assign payments_total = 0 %}
{%-   for payment in invoice.payments %}
{%-     assign payments_total = payments_total | plus: payment.amount %}
h| Payment | {{ payment.date | date: date_format }}
| {{ payment.method }}
| | -{{ payment.amount | format_decimal | number_delimited }}
{%-     assign invoice_memo = payment.memo | default: "" %}
{%-   endfor %}
{%-   assign balance_due = subtotal | minus: payments_total %}
h| Balance Due | | | s| {{ currency_symbol }}{{ balance_due | format_decimal | number_delimited }}
{%- elsif invoice.dates.paid %}
h| Balance Due | | | s| {{ currency_symbol }}0.00
{%- endif %}
|===

{%- if invoice_memo %}
== Memo

{{ invoice_memo }}
{%- endif %}

{% if provider.payment_terms or client.payment_terms or invoice.payment_terms %}
== Payment Terms

{{ invoice.payment_terms | default: client.payment_terms | default: provider.payment_terms }}
{%- endif %}

== Payment Instructions

{% if settings.payment_instructions or client.payment_instructions %}

{% else %}
{{ client.payment_instructions | default: provider.payment_instructions }}
{% else %}
Please remit payment to the following address:

{{ provider.company }} +
{{ provider.address }}
{% endif %}

== Provider Information

Contact::
[horizontal]
Email::: {{ provider.contact.email }}
Phone::: {{ provider.contact.phone }}
{%- if provider.billing %}
Billing::
[horizontal]
Email::: {{ provider.billing.email }}
Phone::: {{ provider.billing.phone }}
{%- endif %}

[horizontal]
EIN:: {{ provider.ein }}